deployment:
  envoyGateway:
    image:
      repository: ${ImageRepository}
      tag: '${ImageTag}'
    imagePullPolicy: Always
    imagePullSecrets: []
    resources:
      limits:
        cpu: 500m
        memory: 1024Mi
      requests:
        cpu: 100m
        memory: 256Mi
  ports:
    - name: grpc
      port: 18000
      targetPort: 18000
    - name: ratelimit
      port: 18001
      targetPort: 18001
  replicas: 1
  pod:
    affinity: {}
    annotations: {}
    labels: {}

config:
  # -- Switch to false to prevent creating the configmap
  enabled: true
  # -- Provide custom name of existing cm, or custom name of cm to be created
  nameOverride: ""
  envoyGateway:
    gateway:
      controllerName: gateway.envoyproxy.io/gatewayclass-controller
    provider:
      type: Kubernetes
    logging:
      level:
        default: info

envoyGatewayMetricsService:
  port: 19001

createNamespace: false

kubernetesClusterDomain: cluster.local

certgen:
  job:
    annotations: {}
    resources: {}
    ttlSecondsAfterFinished: 0
  rbac:
    annotations: {}
    labels: {}
